# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from chat.services.v1 import chatter_pb2 as chat_dot_services_dot_v1_dot_chatter__pb2


class ChatterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinRoom = channel.unary_unary(
                '/chat.services.v1.Chatter/JoinRoom',
                request_serializer=chat_dot_services_dot_v1_dot_chatter__pb2.JoinRoomRequest.SerializeToString,
                response_deserializer=chat_dot_services_dot_v1_dot_chatter__pb2.JoinRoomResponse.FromString,
                )
        self.SendMessage = channel.unary_unary(
                '/chat.services.v1.Chatter/SendMessage',
                request_serializer=chat_dot_services_dot_v1_dot_chatter__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=chat_dot_services_dot_v1_dot_chatter__pb2.SendMessageResponse.FromString,
                )
        self.GetMessages = channel.unary_stream(
                '/chat.services.v1.Chatter/GetMessages',
                request_serializer=chat_dot_services_dot_v1_dot_chatter__pb2.GetMessagesRequest.SerializeToString,
                response_deserializer=chat_dot_services_dot_v1_dot_chatter__pb2.SendMessageRequest.FromString,
                )


class ChatterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def JoinRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinRoom,
                    request_deserializer=chat_dot_services_dot_v1_dot_chatter__pb2.JoinRoomRequest.FromString,
                    response_serializer=chat_dot_services_dot_v1_dot_chatter__pb2.JoinRoomResponse.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=chat_dot_services_dot_v1_dot_chatter__pb2.SendMessageRequest.FromString,
                    response_serializer=chat_dot_services_dot_v1_dot_chatter__pb2.SendMessageResponse.SerializeToString,
            ),
            'GetMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.GetMessages,
                    request_deserializer=chat_dot_services_dot_v1_dot_chatter__pb2.GetMessagesRequest.FromString,
                    response_serializer=chat_dot_services_dot_v1_dot_chatter__pb2.SendMessageRequest.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat.services.v1.Chatter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Chatter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def JoinRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chat.services.v1.Chatter/JoinRoom',
            chat_dot_services_dot_v1_dot_chatter__pb2.JoinRoomRequest.SerializeToString,
            chat_dot_services_dot_v1_dot_chatter__pb2.JoinRoomResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chat.services.v1.Chatter/SendMessage',
            chat_dot_services_dot_v1_dot_chatter__pb2.SendMessageRequest.SerializeToString,
            chat_dot_services_dot_v1_dot_chatter__pb2.SendMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/chat.services.v1.Chatter/GetMessages',
            chat_dot_services_dot_v1_dot_chatter__pb2.GetMessagesRequest.SerializeToString,
            chat_dot_services_dot_v1_dot_chatter__pb2.SendMessageRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
