# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat/core/v1/chat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chat.core.v1 import message_pb2 as chat_dot_core_dot_v1_dot_message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63hat/core/v1/chat.proto\x12\x0c\x63hat.core.v1\x1a\x1a\x63hat/core/v1/message.proto\"\x80\x01\n\x04\x43hat\x12\x0f\n\x07\x63hat_id\x18\x01 \x01(\t\x12\x11\n\tchat_name\x18\x02 \x01(\t\x12\x15\n\ris_group_chat\x18\x03 \x01(\x08\x12\x14\n\x0cparticipants\x18\x04 \x03(\t\x12\'\n\x08messages\x18\x05 \x03(\x0b\x32\x15.chat.core.v1.MessageB\n\xaa\x02\x07\x43hatAppb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat.core.v1.chat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\007ChatApp'
  _globals['_CHAT']._serialized_start=70
  _globals['_CHAT']._serialized_end=198
# @@protoc_insertion_point(module_scope)
